In [8]:
import numpy as np
a= np.array([10,20,30,40,50])
print(a+2)
print(a*3)
print(a/2)

[12 22 32 42 52]
[ 30  60  90 120 150]
[ 5. 10. 15. 20. 25.]


In [12]:
print(a[::-1])
x = np.array([1,2,3,4,5,1,2,1,1,1]) 
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3]) 
values, counts= np.unique(x, return_counts=True)
mfx=values[np.argmax(counts)]
ix=np.where(x==mfx)
print("most frequent in x:",mfx)
print("indices in x:",ix)

values, counts= np.unique(y, return_counts=True)
mfy=values[np.argmax(counts)]
iy=np.where(y==mfy)
print("most frequent in y:",mfy)
print("indices in y:",iy)

[50 40 30 20 10]
most frequent in x: 1
indices in x: (array([0, 5, 7, 8, 9]),)
most frequent in y: 1
indices in y: (array([0, 1, 2]),)


In [17]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
a = arr[0, 1]  
b = arr[2, 0]   
print(a)
print(b)

20
70


In [16]:
abhinav= np.linspace(10, 100, 25)
print("Array:", abhinav)
print("Dimensions:", abhinav.ndim)
print("Shape:", abhinav.shape)
print("Total elements:", abhinav.size)
print("Data type:", abhinav.dtype)
print("Total bytes:", abhinav.nbytes)
transposed = abhinav.reshape(25, 1)
print("Transposed using reshape:", transposed)
print("Using .T attribute (no change on 1-D array):", abhinav.T)

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200
Transposed using reshape: [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Using .T attribute (no change on 1-D array): [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [18]:
ucs420_abhinav = np.array([[10, 20, 30, 40],
                          [50, 60, 70, 80],
                          [90, 15, 20, 35]])
print("Array:", ucs420_abhinav)
print("Mean:", np.mean(ucs420_abhinav))
print("Median:", np.median(ucs420_abhinav))
print("Max:", np.max(ucs420_abhinav))
print("Min:", np.min(ucs420_abhinav))
print("Unique elements:", np.unique(ucs420_abhinav))
reshaped_ucs420_abhinav = ucs420_abhinav.reshape(4, 3)
print("Reshaped (4x3):\n", reshaped_ucs420_abhinav)
resized_ucs420_abhinav = np.resize(ucs420_abhinav, (2, 3))
print("Resized (2x3):\n", resized_ucs420_abhinav)

Array: [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized (2x3):
 [[10 20 30]
 [40 50 60]]
